{
    'name': 'ABS PRM',
    'author': "TH Company",
    'summary': 'ABS PRM',
    'version': '16.0.110524',
    'category': 'AUM Business System/ PRM',
    'website': 'https://aum.edu.vn/',
    'license': 'LGPL-3',
    'depends': ['th_contact',
                'portal',
                'th_setup_parameters',
                'web_domain_field',
                'formio'
                ],
    'data': [
        'data/th_data_module.xml',
        'data/mail_template_update_info.xml',
        'data/code_name_data.xml',
        'data/th_schedule.xml',
        'data/prm_partner_group_data.xml',
        'data/mail_template_notify_duplicate_lead.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'wizard/prm_lead_create_account.xml',
        'views/prm_lead_view.xml',
        'views/prm_level_view.xml',
        'views/th_prm_res_partner.xml',
        'views/prm_reason_quit_view.xml',
        'views/prm_partner_level_view.xml',
        'views/prm_commission_policy_view.xml',
        'views/prm_partner_group_view.xml',
        'views/prm_partner_source_view.xml',
        'views/prm_call_status_view.xml',
        'views/prm_team_view.xml',
        'views/prm_lead_reuse_view.xml',
        'views/pom_lead_view.xml',
        'views/pom_lead_reuse_view.xml',
        'views/th_ownership_unit.xml',
        'views/collaborative_products_view.xml',
        'views/th_formio_builder_view.xml',
        'wizard/prm_assign_leads_view_wizard.xml',
        'wizard/prm_transform_stage_view_wizard.xml',
        'wizard/prm_lead_reuse_view_wizard.xml',
        'wizard/prm_import_view_wizard.xml',
        'views/prm_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'th_prm/static/src/**/*',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
